### ISSUE TITLE
Is it possible to do something similar for other types of call?

### ISSUE THREAD

**Issue by kosso** [dbankier/CoreTelephony-for-Appcelerator-Titanium#4]
Hi,

I use this great module for detecting when an audio recorder or radio app is paused by an incoming phonecall in the pause event. 

Do you know if it's possible to create a module (or Ti SDK 'hack') to detect if an app was paused by an incoming FaceTime call or Siri usage (which also 'pause' an app)?

Cheers! :)
K

**Comment by dbankier** [comment]
Hi Kosso,

iOS supports detecting audio recording interruptions.
See [this](https://developer.apple.com/library/ios/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html) and more specifically [this](https://developer.apple.com/library/ios/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioInterruptions/HandlingAudioInterruptions.html#//apple_ref/doc/uid/TP40007875-CH4-SW1) whis is what you want. I think Ti uses `AVAudioSession` so another module extending Ti to detect interruption and resume should  be possible.

**Comment by kosso** [comment]
Thank you David :)
